# Generated by Django 3.1.4 on 2020-12-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Atlantis', max_length=300)),
                ('name_ar', models.CharField(default='اتلانتس', max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('tel', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('adress', models.CharField(max_length=300)),
                ('adress_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('adress_en', models.CharField(blank=True, max_length=300, null=True)),
                ('tel', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('region_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('n_star', models.PositiveIntegerField(blank=True, null=True)),
                ('coming_soon', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlhotel.group')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=300)),
                ('page_name_en', models.CharField(blank=True, max_length=300, null=True)),
                ('page_name_fr', models.CharField(blank=True, max_length=300, null=True)),
                ('page_name_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlhotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='SousPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spage', models.CharField(blank=True, max_length=300, null=True)),
                ('name_spage_en', models.CharField(blank=True, max_length=300, null=True)),
                ('name_spage_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlhotel.page')),
            ],
        ),
        migrations.CreateModel(
            name='TextSousPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=300)),
                ('texte', models.TextField(blank=True, null=True)),
                ('etiquette', models.CharField(blank=True, max_length=300, null=True)),
                ('position', models.PositiveIntegerField()),
                ('sous_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlhotel.souspage')),
            ],
        ),
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=300)),
                ('texte', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('etiquette', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlhotel.page')),
            ],
        ),
        migrations.CreateModel(
            name='PictureSousPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('etiquette', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('SousPage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlhotel.souspage')),
            ],
        ),
        migrations.CreateModel(
            name='PicturePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('etiquette', models.CharField(max_length=300)),
                ('position', models.PositiveIntegerField()),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlhotel.page')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mail_user', models.CharField(max_length=300)),
                ('phone', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=300)),
                ('request', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlhotel.hotel')),
            ],
        ),
    ]
