# Generated by Django 3.1.4 on 2021-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlhotel', '0004_auto_20210117_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='region_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
