# Generated by Django 3.1.4 on 2021-02-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlhotel', '0005_hotel_region_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('room_type', models.CharField(max_length=100)),
                ('room_price', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlhotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('langue', models.CharField(max_length=20, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlhotel.hotel')),
            ],
        ),
    ]
